[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "rec"
version = "0.1.0"
description = "Run jobs in a distributed, resilient local execution network."
readme = "README.md"
requires-python = ">= 3.10"
dependencies = [
    # REC Core utilities
    ## WASM execution support
    "wasmtime",

    # REC REST API
    ## Web framework and server
    "fastapi",
    "uvicorn",
    ## API features
    "fastapi-pagination",
    "python-multipart",
    "pydantic",
    ## HTTP client
    "requests",
    ## Service discovery
    "zeroconf",
    ## System monitoring
    "psutil",
    ## Concurrency control
    "readerwriterlock",

    # REC DTN
    ## Message serialization
    "msgpack",
    ## Datastore
    "async-tinydb",
    "aiofiles",
    "aiorwlock",
    ## Misc
    "tomlkit",
]
authors = [
    { name = "Philipp Jahn", email = "jahnp@students.uni-marburg.de" },
    { name = "Markus Sommer", email = "msommer@informatik.uni-marburg.de" },
    { name = "Leon Wimbes", email = "wimbes@students.uni-marburg.de" },
]
maintainers = [
    { name = "Markus Sommer", email = "msommer@informatik.uni-marburg.de" },
]
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: MIT License",

    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",

    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
]

[dependency-groups]
dev = [
    "pre-commit",
    "hatchling",
]
lint = [
    "ruff",
    "black",
    "isort",
]
test = [
    "pytest",
    "pytest-cov",
    "pytest-asyncio",
    "hypothesis",
]

[project.scripts]
rec_rest = "rec.run_rest:main"
rec_dtn = "rec.run_dtn:main"

[project.urls]
Repository = "https://github.com/umr-ds/resilient-edge-computing"
Issues = "https://github.com/umr-ds/resilient-edge-computing/issues"

[tool.pytest.ini_options]
pythonpath = ["."]
